name: labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - name: Retrieve existing comments
        id: get-comments
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            return response.data;

      - name: Check for existing comment
        id: check-comment
        run: |
          const existingComment = context.steps.get-comments.outputs.result.find(comment => {
            // Compare the comment body or other relevant information
            return comment.body.includes('This PR is extremely big! Please, split it');
          });

          echo "::set-output name=commentExists::${{ Boolean(existingComment) }}"

      - name: Publish comment if not already exist
        if: steps.check-comment.outputs.commentExists != 'true'
        run: |
          # Publish the comment using the appropriate action or GitHub API call
          # ...

      - name: Label PR size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '100'
          m_label: 'size/m'
          m_max_size: '500'
          l_label: 'size/l'
          l_max_size: '1000'
          xl_label: 'size/xl'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          github_api_url: 'api.github.com'
          files_to_ignore: ''

      - name: Continue with other steps
        run: |
          # Other steps in the workflow
          # ...
